Repository ManageIQ/manageiq-providers-ibm_power_vc, pull requests merged in 2021-12, with the labels that each got.

#31 Creating dynamic VM for rails spec test
  .gitignore
  .yamllint
  config/secrets.defaults.yml
  lib/tasks/README.md
  lib/tasks_private/terraform/main.tf
  lib/tasks_private/terraform/provider.tf
  lib/tasks_private/terraform/provision.rake
  lib/tasks_private/terraform/terraform.tfvars
  lib/tasks_private/terraform/variables.tf
  manageiq-providers-ibm_power_vc.gemspec
  spec/models/manageiq/providers/ibm_power_vc/cloud_manager/refresher_spec.rb
  spec/models/manageiq/providers/ibm_power_vc/cloud_manager/state.yml
  spec/vcr_cassettes/manageiq/providers/ibm_power_vc/cloud_manager/refresher.yml
Labels: enhancement, test

#33 converting supported_for_create to supports :create
  app/models/manageiq/providers/ibm_power_vc/cloud_manager.rb
Labels: enhancement

#34 Expect the proper cloud-tenant class name
  app/models/manageiq/providers/ibm_power_vc/cloud_manager/template.rb
  spec/models/manageiq/providers/ibm_power_vc/cloud_manager/refresher_spec.rb
Labels: bug

#28 added the advanced settings for powervc
  app/models/manageiq/providers/ibm_power_vc/inventory/parser/cloud_manager.rb
  app/models/manageiq/providers/ibm_power_vc/inventory/persister/cloud_manager.rb
  lib/tasks_private/terraform/provision.rake
  spec/models/manageiq/providers/ibm_power_vc/cloud_manager/state.yml
  spec/vcr_cassettes/manageiq/providers/ibm_power_vc/cloud_manager/refresher.yml
Labels: enhancement

#30 Add secrets config to git ignore
  .gitignore
Labels: bug, developer
