Repository ManageIQ/manageiq-providers-ibm_power_vc, pull requests merged in 2022-10, with the labels that each got.

#70 Subclass Snapshot under IbmPowerVc::CloudManager
  app/models/manageiq/providers/ibm_power_vc/cloud_manager.rb
  app/models/manageiq/providers/ibm_power_vc/cloud_manager/snapshot.rb
Labels: bug

#62 placement group for power vc
  app/models/manageiq/providers/ibm_power_vc/cloud_manager.rb
  app/models/manageiq/providers/ibm_power_vc/cloud_manager/placement_group.rb
Labels: enhancement

#72 Add Server Groups to VCR
  spec/vcr_cassettes/manageiq/providers/ibm_power_vc/cloud_manager/refresher.yml
Labels: bug, test
