Repository ManageIQ/manageiq-providers-ibm_power_vc, pull requests merged in 2022-03, with the labels that each got.

#50 Fix PowerVC reports
  app/models/manageiq/providers/ibm_power_vc/inventory/parser/cloud_manager.rb
  content/reports/1000_IBM Power - Virtual Machines/010_PowerVC VMs.yaml
Labels: bug, najdorf/yes?

#54 added correct function include?
  app/models/manageiq/providers/ibm_power_vc/cloud_manager.rb
Labels: bug, najdorf/yes?

#52 Adding Cloud Volume subclasses in the IbmPowerVc CinderManager
  app/models/manageiq/providers/ibm_power_vc/storage_manager/cinder_manager.rb
  app/models/manageiq/providers/ibm_power_vc/storage_manager/cinder_manager/cloud_volume.rb
  app/models/manageiq/providers/ibm_power_vc/storage_manager/cinder_manager/cloud_volume_backup.rb
  app/models/manageiq/providers/ibm_power_vc/storage_manager/cinder_manager/cloud_volume_snapshot.rb
  app/models/manageiq/providers/ibm_power_vc/storage_manager/cinder_manager/cloud_volume_type.rb
Labels: bug

#53 adding Cloud Network subclasses in IbmPowerVC NetworkManager
  app/models/manageiq/providers/ibm_power_vc/network_manager.rb
  app/models/manageiq/providers/ibm_power_vc/network_manager/cloud_network.rb
  app/models/manageiq/providers/ibm_power_vc/network_manager/cloud_subnet.rb
  app/models/manageiq/providers/ibm_power_vc/network_manager/floating_ip.rb
  app/models/manageiq/providers/ibm_power_vc/network_manager/network_port.rb
  app/models/manageiq/providers/ibm_power_vc/network_manager/network_router.rb
  app/models/manageiq/providers/ibm_power_vc/network_manager/security_group.rb
Labels: enhancement

#55 adding Cloud Network subclasses in IbmPowerVC NetworkManager
  app/models/manageiq/providers/ibm_power_vc/network_manager.rb
  app/models/manageiq/providers/ibm_power_vc/network_manager/floating_ip.rb
Labels: bug
