Repository ManageIQ/manageiq-providers-ibm_power_vc, pull requests merged in 2022-02, with the labels that each got.

#39 Remove Hakiri
  README.md
Labels: cleanup, developer

#41 Switch to GitHub Actions
  .github/workflows/ci.yaml
  .travis.yml
  README.md
  bin/before_install
  bin/ci/after_script
  bin/setup
  manageiq-providers-ibm_power_vc.gemspec
Labels: developer, test

#42 Add Build History Graph to README.md
  README.md
Labels: developer, test

#45 disable choice of SSH pw for image import on reg. form
  app/models/manageiq/providers/ibm_power_vc/cloud_manager.rb
Labels: bug

#44 hiding the RC file location field
  app/models/manageiq/providers/ibm_power_vc/cloud_manager.rb
Labels: bug

#47 Cron for GitHub Actions
  .github/workflows/ci.yaml
Labels: developer, test
