Repository ManageIQ/manageiq-providers-ibm_power_vc, pull requests merged in 2022-05, with the labels that each got.

#58 Update apt-cache before running apt-get install
  bin/before_install
Labels: bug, test

#57 Add manual option for CI github workflow
  .github/workflows/ci.yaml
Labels: test

#38 image import workflow PVS-to-PVC image import
  app/helpers/manageiq/providers/ibm_power_vc/toolbar_overrides/ems_cloud_center.rb
  app/javascript/components/pvc-import-image-form/pvc-import-image-form.jsx
  app/javascript/components/pvc-import-image-form/pvc-import-image-form.schema.js
  app/javascript/packs/component-definitions-common.js
  app/models/manageiq/providers/ibm_power_vc/cloud_manager.rb
  app/models/manageiq/providers/ibm_power_vc/cloud_manager/pvc_image_import_workflow.rb
  app/models/manageiq/providers/ibm_power_vc/cloud_manager/pvc_image_import_workflow/image_import_auth.rb
  app/models/manageiq/providers/ibm_power_vc/cloud_manager/pvc_image_import_workflow/image_import_credential.rb
  app/models/manageiq/providers/ibm_power_vc/cloud_manager/pvc_image_import_workflow/pvc_image_import_button.rb
  app/models/manageiq/providers/ibm_power_vc/cloud_manager/pvc_image_import_workflow/pvc_import_dispatcher.rb
  app/models/manageiq/providers/ibm_power_vc/cloud_manager/pvc_image_import_workflow/ssh_pkey_auth.rb
  app/models/manageiq/providers/ibm_power_vc/cloud_manager/pvc_image_import_workflow/ssh_pkey_credential.rb
  app/models/manageiq/providers/ibm_power_vc/cloud_manager/template.rb
  content/ansible_runner/image-copy-pvs-to-pvc.yml
  content/ansible_runner/roles/image-copy-pvs-to-pvc/files/download_ova_from_bucket.py
  content/ansible_runner/roles/image-copy-pvs-to-pvc/files/sample.txt
  content/ansible_runner/roles/image-copy-pvs-to-pvc/tasks/execute.yml
  content/ansible_runner/roles/image-copy-pvs-to-pvc/tasks/main.yml
  content/ansible_runner/roles/image-copy-pvs-to-pvc/tasks/validate.yml
  content/ansible_runner/roles/image-copy-pvs-to-pvc/templates/credentials.aes
  content/ansible_runner/roles/image-copy-pvs-to-pvc/vars/main.yml
Labels: enhancement, najdorf/yes?

#59 inheriting image import job and dispatcher from base
  app/models/manageiq/providers/ibm_power_vc/cloud_manager/pvc_image_import_workflow.rb
  app/models/manageiq/providers/ibm_power_vc/cloud_manager/pvc_image_import_workflow/pvc_import_dispatcher.rb
Labels: najdorf/yes?
