Repository ManageIQ/manageiq-providers-ibm_power_vc, pull requests merged in 2023-06, with the labels that each got.

#87 Update VCRs for fog-openstack v1
  spec/models/manageiq/providers/ibm_power_vc/cloud_manager/refresher_spec.rb
  spec/spec_helper.rb
  spec/vcr_cassettes/manageiq/providers/ibm_power_vc/cloud_manager/refresher.yml
Labels: test, petrosian/yes?

#88 add log level for IbmPowerVc
  config/settings.yml
Labels: bug, petrosian/yes?

#89 Ibm PowerVc events
  app/models/manageiq/providers/ibm_power_vc/cloud_manager.rb
  app/models/manageiq/providers/ibm_power_vc/cloud_manager/event_target_parser.rb
Labels: enhancement
